### ISSUE TITLE
Initial time shows as 12:00, when it's actually 00:00

### ISSUE THREAD

**Issue by SmileyChris** [priyank-p/simplepicker#12]
At a quick glance, it looks like that this should be set in `updateDateComponents`

**Comment by priyank-p** [comment]
@SmileyChris thanks for the report! This should be easy to fix.

**Comment by priyank-p** [comment]
Actually, I don't think there is a problem here because we display `12:00 AM` or `12:00 PM`. It wouldn't make sense to display `00:00 AM` here. Does that make sense @SmileyChris or this is still a user experience issue?

**Comment by SmileyChris** [comment]
it's showing as 12pm, when it's actually 12am. The bigger issue here is
that it's not taking into account the initial datetime, it's just the
default that the value was set to in the UI.

I noticed this because I changed the initial datetime after initializing
and saw  in code that the time values are never actually being set

**Comment by priyank-p** [comment]
Ah, got it. The time UI currently does not take into account the current time rather just sets it to 12 PM.

**Comment by priyank-p** [comment]
Hello @SmileyChris, this should be fixed by e4d34992f37c7ff45dd1f0033b7dc04b5e3be6b1. Can you double check. I am doing a 2.0.2 release now with the fix.
