### ISSUE TITLE
Disable date section

### ISSUE THREAD

**Issue by NeishaS** [priyank-p/simplepicker#19]
Hello Priyank,
Is it possible to have just the Time picker with this tool?
I would really love to use this plugin in my current project since it is already being used in my other projects.
I just came across the need to add separate date and time input fields for the users.

Thanks.

**Comment by NeishaS** [comment]
Hi! 
I was able to just find and hide the calendar button and click the time button before opening the picker.

**Comment by priyank-p** [comment]
@NeishaS let me know if this is something that can be made clear in the readme.
