### ISSUE TITLE
Picker is always inserted directly under document body

### ISSUE THREAD

**Issue by epiqu1n** [priyank-p/simplepicker#23]
Regardless of if an element or a selector is passed to the constructor, the picker is always inserted directly under the body instead of replacing or inserting into (either would be fine) the element.

![image](https://user-images.githubusercontent.com/1347847/88498392-fde36580-cf90-11ea-8359-c7222589f35c.png)
![image](https://user-images.githubusercontent.com/1347847/88498408-05a30a00-cf91-11ea-9bc7-c4306636b802.png)

Tested on latest versions of Chrome and Firefox

**Comment by priyank-p** [comment]
This fixed by 8cde1bf6d0b5a38906b6df1aaa38bce3bdaa86b0 in master. I manually tested all the combinations of the constructor this time with correct types.

**Comment by priyank-p** [comment]
OK, I released a new version to npm. It would be great if you can verify all the fixes to issues you have reported @epiqu1n and thanks again for the reports.

**Comment by epiqu1n** [comment]
All of the issues I've reported do seem to be fixed, thank you very much.

**Comment by priyank-p** [comment]
Awesome!
