### ISSUE TITLE
Simplepicker modifying other tables on page

### ISSUE THREAD

**Issue by epiqu1n** [priyank-p/simplepicker#25]
After much confusion, I have discovered that simplepicker is modifying other parts of the document.

Specifically, I have a table in which rows are displayed as flex.  However, the last row of the table keeps having `style="display: table-row;"` set on it, despite the fact that it and the simplepicker-wrapper have different parents, resulting in this:
![image](https://user-images.githubusercontent.com/1347847/91256135-8b52da80-e734-11ea-8d16-d6e182b21588.png)

Not initializing simplepicker in my code stops this behavior from happening.

**Comment by priyank-p** [comment]
Oh ok, I found the bug thanks for the report. I wrote the code in a way it only selects the elements inside the simplepicker html we insert but it has a bug where scope to the parent element instead of the simplepicker element itself.

**Comment by priyank-p** [comment]
This is fixed in master but re-opening until I make a release.
