### ISSUE TITLE
When using index-multi.html on local wampserver, arrows jumps 2 months ahead

### ISSUE THREAD

**Issue by dudanesk** [priyank-p/simplepicker#35]
When I use the "multi picker on same page" on https://priyank-p.github.io/simplepicker/index-multi.html, it works beautifully. But when I import index-multi.html on my local website using wampserver without changing or modifying any of the code at all, it doesn't work properly anymore. The arrow jumps 2 months ahead (from april to june to august etc... and same going backward). I'm clueless. Again, I haven't changed the code at all, I just copied index-multi.html on my local folder and it won't work like it does on https://priyank-p.github.io/simplepicker/index-multi.html. Any ideas?

**Comment by priyank-p** [comment]
Did you copy the `dist/simplepicker.js` and `dist/simplepicker.css` along with the `index-multi.html`? The GitHub pages website uses the files present here on GitHub I just mentioned before so that needs to be the same. My guess is that is outdated somehow?

**Comment by dudanesk** [comment]
I did move all the current pages on GitHub along with index-multi.html
But I managed to get it to work by simply creating a new folder to move my local website in. The website is the exact same without any modifications, but here in this new location, simplepicker works as intended. I can't wrap my head around that, but everything works now and that's all I care about :-)
Thanks you so much for getting back to me and trying to help out, and an even bigger thank you for sharing your whole simplepicker project, which I am delighted with

**Comment by priyank-p** [comment]
I am glad to hear you resolve the issue! And thank you for your kind words :)
