### ISSUE TITLE
Two pickers result in empty calendar

### ISSUE THREAD

**Issue by qyzh195** [priyank-p/simplepicker#5]
Instantiating two date picker, leaving the first constructor empty and pass an element to the second as the README demonstrates, the first date picker would have an empty calendar when opened. After switching month, the date list comes back.
Is it a bug or the way I use is not correct?

Thanks,

**Comment by priyank-p** [comment]
@qyzh195 my hunch is that this is a bug. I will try to reproduce this and get back to you soon. If this is a bug I think I know what the fix would be. Thanks for the report!

**Comment by priyank-p** [comment]
OK, this is definitely a bug.

**Comment by priyank-p** [comment]
I fixed the issue. Will release a bug fix version soon.

**Comment by priyank-p** [comment]
@qyzh195 I have released a new version `v1.2.4` which fixes this issue.
