### ISSUE TITLE
Firefox NAN

### ISSUE THREAD

**Issue by Rimander** [priyank-p/simplepicker#6]
If use firefox.
1. Open Calendar
2. Change month
3. Change to actual month
4. Only view Nan Nan

**Comment by priyank-p** [comment]
@Rimander can you post a screenshot, and provide the console logs? Also which firefox version are you using?

I am pretty sure simplepicker works fine on firefox, but will try out firefox today and see.

**Comment by limjinsun** [comment]
It happens to me too. in Chrome it works fine, but in FF it gives error when you select February. 
<img width="378" alt="screenshot 2019-02-13 at 01 44 57" src="https://user-images.githubusercontent.com/11390856/52680664-31633900-2f31-11e9-82c3-2cd3440aeabf.png">

**Comment by priyank-p** [comment]
OK, finally got time to debug this. I can reproduce this in firefox but not in chrome and only happens in February (I think just current month!). Don't have solid idea what it might be currently.

**Comment by priyank-p** [comment]
Done debugging, apparently `new Date('13 Febuary 2019 12:00 PM')` works in chrome and not in firefox. Looking into why it doesn't work...

**Comment by limjinsun** [comment]
reference this - https://stackoverflow.com/questions/3257460/new-date-is-working-in-chrome-but-not-firefox

**Comment by priyank-p** [comment]
@limjinsun Yep, thanks for the reference, I am planning to fix this by passing values as `new Date(13, 2, 2019, 12, 00)`. I expect a fix soon followed by a release of new version on npm.

**Comment by limjinsun** [comment]
Thanks. I will look forward to it.

**Comment by priyank-p** [comment]
(Doing a release shortly! I fixed this issue in master)

**Comment by priyank-p** [comment]
New release (v2.0.0) is out. Thanks @Rimander for the report and @limjinsun for all the help :)
