### ISSUE TITLE
Reset date and time

### ISSUE THREAD

**Issue by mnagon** [priyank-p/simplepicker#9]
There should be a method to reset the date and time to default (current time).

or should be a method to set the date and time for picker.

**Comment by priyank-p** [comment]
This would be a great addition. Any additional thoughts on whether the "Cancel" button should do this by default?

**Comment by mnagon** [comment]
It's will be great if we have some method to set simplepicker value like
eg. 

simplepicker.setDate('11-12-19') 

or

 simplepicker.setTime('15:30')

to set default date and time for simplepicker

or something like 

simplepicker.clear()

to clear date-time has picked from last submit.

I think these methods are really useful

**Comment by priyank-p** [comment]
Quick update: I implemented a `reset` method that will allow resetting the date. Next, I am going to work on a select date and time method.

**Comment by priyank-p** [comment]
Hello @mnagon, I published a new version today v2.0.1 that includes the `reset` method. Unfortunately, I did not get time to work on other methods like `setTime` and `setDate`.

I will try to get others implemented soon until then I hope reset is good enough.

**Comment by gstcyr** [comment]
It appears that the new reset method doesn't work when passing in a date, I think it's because the dist folder wasn't updated

**Comment by priyank-p** [comment]
@gstcyr I still have to do a release. Typically the `dist` is updated when I create a new release and get packed into the new npm release. I'll try to do a release today.

Do you use SimplePicker directly by getting code from GitHub? If so I can update the docs on how one can build the assets from the master.

**Comment by gstcyr** [comment]
I'm using yarn, but I can run the build script in my node_modules/simplepicker directory locally until you get the release out.

**Comment by priyank-p** [comment]
For yarn, `yarn build` should do it.

**Comment by priyank-p** [comment]
Oh, also you probably need to do: `yarn install https://github.com/priyank-p/simplepicker` so it installs the latest code from GitHub.

**Comment by gstcyr** [comment]
I'm getting some build errors, but in the meantime I've solved my issue by destroying the existing picker on close and creating a new one each time and passing in 'selectedDate'.

**Comment by priyank-p** [comment]
@gstcyr @mnagon I published `2.0.2` with this feature. Please, let me know if you encounter any issues with the new release. I am writing the changelog and description of it in the release page shortly.

**Comment by priyank-p** [comment]
Also, thanks @crossleyjuan for implementing the feature!
